export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';

export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
